#' Analyze single interaction term in linear regression
#'
#' @param data - prepared data generated by function prepare_data (only contains binary variables and response variable )
#' @param interaction_matrix - Interaction Matrix generated by create_interaction_matrix
#' @param response_var - response variable y
#' @return - full_results. A list where each element is a regression coefficient summary for each interaction term in the interaction matrix.
#'
#'
#' @export
#'
#' @examples
#' set.seed(1234)
#' n <- 100
#' v1 = rbinom(n, 1, 0.4)
#' v2 <- rbinom(n, 1, 0.5)
#' v3 <- rbinom(n, 1, 0.6)
#' v4 = rnorm(n)
#' v5 = rbinom(n, 1, 0.6)
#' interaction_effect1 <- v2 * v3
#' interaction_effect2 <- v1 * v3
#' y1 <- 2 * v1 + 2 * v2 + 2 * v3 + 4 * v4 + 3 * v5 + 100 * interaction_effect1 + 100 * interaction_effect2 + rnorm(n,mean=0,sd=1)
#' data <- data.frame(y = y1, v1 = v1, v2 = v2, v3 = v3, v4 = v4, v5 = v5)
#' prepared_data <- prepare_data(data, "y")
#' interaction_matrix <- create_interaction_matrix(prepared_data, "y")
#'
#'
#' #The way we generate model would be y = v1 + v2 + v3 + v5 + v1 * v2 ,
#'  #y = v1 + v2 + v3 + v5 + v1 * v3,...,etc
#' full_results <- analyze_interactions(prepared_data, interaction_matrix, "y")
#' print(full_results)
#'

analyze_interactions <- function(data, interaction_matrix, response_var) {
  full_results <- list()

  for (interaction_term in colnames(interaction_matrix)) {
    response_var <- as.character(response_var)
    predictors <- names(data)[which(names(data) != response_var)]
    formula_str <- paste(response_var, "~", paste(predictors, collapse = " + "), "+", interaction_term)
    formula <- as.formula(formula_str)

    model_data <- cbind(data, interaction_matrix)

    # fit linear regression for each interaction term
    model <- lm(formula, data = model_data)
    coefficients_summary <- summary(model)$coefficients

    full_results[[interaction_term]] <- coefficients_summary
  }

  full_results
}














