#' Create Interaction Matrix
#'
#' @param data - prepared data generated by function prepare_data (only contains binary variables and response variable )
#' @param response_var - response variable y
#'
#' @return - Interaction Matrix
#' @export
#'
#' @examples
#'
#' set.seed(1234)
#' n <- 100
#' v1 = rbinom(n, 1, 0.4)
#' v2 <- rbinom(n, 1, 0.5)
#' v3 <- rbinom(n, 1, 0.6)
#' v4 = rnorm(n)
#' v5 = rbinom(n, 1, 0.6)
#' interaction_effect1 <- v2 * v3
#' interaction_effect2 <- v1 * v3
#' y1 <- 2 * v1 + 2 * v2 + 2 * v3 + 4 * v4 + 3 * v5 + 100 * interaction_effect1 + 100 * interaction_effect2 + rnorm(n,mean=0,sd=1)
#' data <- data.frame(y = y1, v1 = v1, v2 = v2, v3 = v3, v4 = v4, v5 = v5)
#' prepared_data <- prepare_data(data, "y")
#' interaction_matrix <- create_interaction_matrix(prepared_data, "y")
#' print(head(interaction_matrix))
#'
#'
create_interaction_matrix <- function(data, response_var) {
  predictors <- setdiff(names(data), response_var)
  predictor_matrix <- as.matrix(data[predictors])

  # vectorization for all possible interaction term
  num_predictors <- ncol(predictor_matrix)
  num_combinations <- num_predictors * (num_predictors - 1) / 2


  interaction_matrix <- matrix(nrow = nrow(data), ncol = num_combinations)
  col_names <- vector("list", num_combinations)

  # name col
  col_index <- 1
  for (i in 1:(num_predictors - 1)) {
    for (j in (i + 1):num_predictors) {
      interaction_matrix[, col_index] <- predictor_matrix[, i] * predictor_matrix[, j]
      col_names[[col_index]] <- paste(colnames(predictor_matrix)[i], "*", colnames(predictor_matrix)[j])
      col_index <- col_index + 1
    }
  }

  colnames(interaction_matrix) <- unlist(col_names)
  interaction_matrix
}

