#' Final Regression Model Summary
#' @param data - prepared data generated by function prepare_data (only contains binary variables and response variable )
#' @param response_var - response variable y
#' @return Final Regression Model Summary
#' @export
#' @examples
#' set.seed(1234)
#' n <- 100
#' v1 = rbinom(n, 1, 0.4)
#' v2 <- rbinom(n, 1, 0.5)
#' v3 <- rbinom(n, 1, 0.6)
#' v4 = rnorm(n)
#' v5 = rbinom(n, 1, 0.6)
#' interaction_effect1 <- v2 * v3
#' interaction_effect2 <- v1 * v3
#' y1 <- 2 * v1 + 2 * v2 + 2 * v3 + 4 * v4 + 3 * v5 +
#' 100 * interaction_effect1 + 100 * interaction_effect2 + rnorm(n,mean=0,sd=1)
#' data <- data.frame(y = y1, v1 = v1, v2 = v2, v3 = v3, v4 = v4, v5 = v5)
#' prepared_data <- prepare_data(data, "y")
#' interaction_matrix <- create_interaction_matrix(prepared_data, "y")
#' full_results <- analyze_interactions(prepared_data, interaction_matrix, "y")
#' significant_interactions <- extract_significant(full_results)
#' fit_final_regression <- final_regression(prepared_data, "y")
#' fit_final_regression

final_regression <- function(data, response_var) {

  significant_terms <- unique(significant_interactions$term)


  formula_str <- paste(response_var, "~", paste(significant_terms, collapse = " + "))
  formula <- as.formula(formula_str)


  final_model <- lm(formula, data = prepared_data)
  summary_final_model <- summary(final_model)

  return(summary_final_model)
}
