#' Interaction Effects Plots
#'
#' @param data - prepared data generated by function prepare_data (only contains binary variables and response variable )
#' @param significant_interactions - significant interaction terms' p-values and their names generated by extract_significant
#'
#' @return plots of interaction terms
#' @export
#'
#' @examples
#' #' set.seed(1234)
#' n <- 100
#' v1 = rbinom(n, 1, 0.4)
#' v2 <- rbinom(n, 1, 0.5)
#' v3 <- rbinom(n, 1, 0.6)
#' v4 = rnorm(n)
#' v5 = rbinom(n, 1, 0.6)
#' interaction_effect1 <- v2 * v3
#' interaction_effect2 <- v1 * v3
#' y1 <- 2 * v1 + 2 * v2 + 2 * v3 + 4 * v4 + 3 * v5 + 100 * interaction_effect1 + 100 * interaction_effect2 + rnorm(n,mean=0,sd=1)
#' data <- data.frame(y = y1, v1 = v1, v2 = v2, v3 = v3, v4 = v4, v5 = v5)
#' prepared_data <- prepare_data(data, "y")
#' interaction_matrix <- create_interaction_matrix(prepared_data, "y")
#' full_results <- analyze_interactions(prepared_data, interaction_matrix, "y")
#' significant_interactions <- extract_significant_p_values(full_results)
#' fit_final_regression <- final_regression(prepared_data, "y")
#' plots <- plot_interaction_effects(prepared_data, significant_interactions)
#' plots
#' do plots in R-markdown if you want to see all plots in 1 times.


plot_interaction_effects <- function(data, significant_interactions) {
  plots <- list()
  interaction_terms <- significant_interactions$term

  for (term in interaction_terms) {
    variables <- strsplit(term, " \\* ")[[1]]
    grouped_data <- data %>%
      group_by(across(all_of(variables))) %>%
      summarise(y_groups = mean(y, na.rm = TRUE), .groups = 'drop')

    # Plot 1: First variable on x-axis
    plot1 <- ggplot(grouped_data, aes(x = .data[[variables[1]]], y = y_groups, color = as.factor(.data[[variables[2]]]))) +
      geom_line(aes(group = .data[[variables[2]]])) +
      geom_point() +
      labs(title = paste("Interaction Effect:", term))

    # Plot 2: Second variable on x-axis
    plot2 <- ggplot(grouped_data, aes(x = .data[[variables[2]]], y = y_groups, color = as.factor(.data[[variables[1]]]))) +
      geom_line(aes(group = .data[[variables[1]]])) +
      geom_point() +
      labs(title = paste("Interaction Effect:", term))

    plots[[term]] <- list(plot1, plot2)
  }

  return(plots)
}

